refactor decoders to non-meta-programming-style.
Byzanteam/postgrex_wal pull request #13
Opened 2022-12-12 05:51 UTC by json2008

- [] rename decoder's file names and module names
- [] transform to code to non-meta-programming style

2022-12-12 07:45 UTC, json2008 commented
- 本地的开发环境中，提交前必需格式化: mix format --check-formatted，
- 提交前必需本地做:  mix credo --strict

此前没配置好，导致推送过来的，ci检测失败。现在已经改过来了。

2022-12-12 08:04 UTC, json2008 commented
@fahchen ，我自己 review 这个 PR，虽然已经很小心，但也发现： 重构原来的 decoder 似乎应该是单独的一个 PR。
添加：测试，以及，补缺的几个decoder，应该另开一个 PR ？

我给合二为一了。:)

2022-12-12 08:48 UTC, fahchen requested changes

2022-12-12 08:48 UTC, fahchen commented on lib/postgrex_wal/message/relation.ex
> +  def decode(<<id::32, rest::binary>>) do
这里的 decode function 写一下 `@impl true` 吧

2022-12-12 08:48 UTC, fahchen commented on lib/postgrex_wal/message/truncate.ex
> +  defstruct ~W[number_of_relations options truncated_relations]a
使用 typestruct 定义

2022-12-12 08:48 UTC, fahchen commented on lib/postgrex_wal/messages.ex
> +  end
```elixir
for {key, module} <- %{"B" => Begin, "C" => Commit} do
  def decode(<<unquote(key)::binary-1, payload::binary>>) do
    unquote(module).decode(payload)
  end
end

2022-12-12 08:48 UTC, fahchen commented on test/decoders_test.exs
> +             xid: _
对应的 value 的内容也测试一下吧

2022-12-12 08:49 UTC, fahchen commented
> @fahchen ，我自己 review 这个 PR，虽然已经很小心，但也发现： 重构原来的 decoder 似乎应该是单独的一个 PR。 添加测试，单独做一个 PR ？， 补缺的几个decoder，应该另开一个 PR ？
> 
> 我给合三为一了。是这样吗？

可以，这个 PR 的测试就先这样写吧，下一个 PR 把真实的数据库引入进来做一下集成测试

2022-12-12 09:10 UTC, json2008 commented on lib/postgrex_wal/message/relation.ex
> +  def decode(<<id::32, rest::binary>>) do
好。

2022-12-12 09:11 UTC, json2008 commented on lib/postgrex_wal/message/truncate.ex
> +  defstruct ~W[number_of_relations options truncated_relations]a
ok

2022-12-12 09:12 UTC, json2008 commented on lib/postgrex_wal/messages.ex
> +  end
学习了。

2022-12-12 11:43 UTC, json2008 commented
@fahchen  
按 review 的意见，我改写了 test， 用match?/2 取代了 =
对值进行的检测。目前的检测比较简单。
待 decode 结构确定后，会再次重构 test的检测。

2022-12-12 11:49 UTC, fahchen commented
> @fahchen  
> 
> 按 review 的意见，我改写了 test， 用match?/2 取代了 =
> 
> 对值进行的检测。目前的检测比较简单。
> 
> 待 decode 结构确定后，会再次重构 test的检测。

1. 谁提的问题就由谁resolve
2. 没有被resolve的就是有问题的，请在对应的conversation处回复

2022-12-12 11:51 UTC, fahchen commented on test/decoders_test.exs
> +               xid: c
这里可以断言对应的值吧

2022-12-12 12:24 UTC, json2008 commented
> 

ok。后面就知道了。

2022-12-12 12:30 UTC, fahchen commented on test/decoders_test.exs
> +             when a == 48_453_656 and b == 723_794_924_203_137 and c == 3_557,
```suggestion
               final_lsn: 48_453_656,
               commit_timestamp: 723_794_924_203_137,
               xid: 3_557
             },
```

2022-12-12 12:34 UTC, json2008 commented on test/decoders_test.exs
> +             when a == 48_453_656 and b == 723_794_924_203_137 and c == 3_557,
ok。改bug改晕头了。我立即去调整下。

2022-12-12 13:37 UTC, json2008 commented on test/decoders_test.exs
> +             when is_list(a) and length(a) == 7,
ok。我来 fix

2022-12-12 14:49 UTC, json2008 commented
### 元编程 vs 非元编程。

```elixir
defmodule PostgrexWal.Messages do
  @moduledoc false

  alias PostgrexWal.Message.{
    Begin,
    Commit,
    Delete,
    Insert,
    Origin,
    Relation,
    Truncate,
    Type,
    Update
  }

  @modules %{
    ?B => Begin,
    ?C => Commit,
    ?D => Delete,
    ?I => Insert,
    ?O => Origin,
    ?R => Relation,
    ?T => Truncate,
    ?Y => Type,
    ?U => Update
  }

  # meta-programming-style
  for {key, module} <- @modules do
    def decode(<<unquote(key)::8, payload::binary>>) do
      unquote(module).decode(payload)
    end
  end

  # non-meta-programming-style
  # def decode(<<key::8, payload::binary>>), do: @modules[key].decode(payload)
end
```

个人感觉，在这个场景中，非元编程：更简单、直观。
易理解，且不易出错。
但掌握元编程的技巧，是非常有必要的。在某些情况下，能更加的 concisely coding。

2022-12-13 01:36 UTC, fahchen commented
元编程生成的方法可读性其实不低的，模式匹配在 elixir 里面是很常见的用法。

2022-12-13 01:37 UTC, fahchen requested changes

2022-12-13 01:37 UTC, fahchen commented on test/decoders_test.exs
> +               data: a,
```suggestion
               data: ^data,
```

2022-12-13 01:37 UTC, json2008 commented
### 怪异的编译出错：

![lh7DvoqQwZ](https://user-images.githubusercontent.com/624775/207204451-46a7f211-c57d-47cf-9192-29a7a49156b7.jpg)

> ** (CompileError) lib/postgrex_wal/messages.ex:31: literal string in bitstring supports only endianness and type specifiers, which must be one of: little, big, native, utf8, utf16, utf32, bits, bytes, binary or bitstring

### 按如下修改调整一下，就编译成功了。（alias 必需要放在 @modules 之前，否则 warning ?）。

![261cqF94wY](https://user-images.githubusercontent.com/624775/207204597-788b61af-13f0-46ad-9544-12a916bb5628.jpg)

2022-12-13 02:04 UTC, fahchen commented
没啥问题了，重做一下 commits 吧

2022-12-13 02:10 UTC, json2008 commented on test/decoders_test.exs
> +               data: a,
Done

2022-12-13 02:15 UTC, json2008 commented
@fahchenok

如果没其它，请 approve 一下。我将此 PR 做 squash merge 到 main 上。

2022-12-13 02:26 UTC, merged