feat:  PostgrexWal.Broadway.Producer
Byzanteam/postgrex_wal pull request #16
Opened 2022-12-27 13:35 UTC by json2008

- [ ] 构建 `PostgrexWal.Broadway.Producer`
- [ ] 完善 `ack` 机制
- [ ] 测试

2022-12-28 09:38 UTC, json2008 commented
@fahchen 

实现了初步的 `pg_replication_ack` 机制。

- [x] 可实现用户指定的 `ack`， 未被确认的 `event`，下次 `reload` 时，还会再送。不会消失。
- [x] `in_transaction` 的状态处理，也实现在里面。 
- [ ]  仅手工测试。正式的测试，稍后。

2022-12-28 09:50 UTC, fahchen reviewed
参考下这个 https://github.com/supabase/realtime/tree/develop/lib/extensions/postgres_cdc_stream

2022-12-28 09:50 UTC, fahchen commented on mix.exs
> +        "format --check-formatted",
```suggestion
        "format --check-formatted",
```

2022-12-28 09:50 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +  end
用 Postgrex.ReplicationConnection 的 lsn 的 encode/decode function 吧

2022-12-28 09:50 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +        ?S -> %{state | in_transaction: true}
transaction 可以嵌套的，这里怎么处理呢？

2022-12-28 09:50 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +        {:in_transaction, payload}
在 transaction 中，会出现一些没有 transaction_id 的 message 吗？

2022-12-28 09:54 UTC, fahchen reviewed
现在的实现没看到 broadway.producer 的相关逻辑哦，你这个 PR 的范围要不要改一下哦

2022-12-28 09:54 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +      ]
这些不应该写死了

2022-12-28 09:54 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +    send(__MODULE__, {:ack, wal})
名字不可以用 `__MODULE__`，因为我们会起多个 source

2022-12-28 09:54 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +      "START_REPLICATION SLOT myslot1 LOGICAL 0/0 (proto_version '2', publication_names '#{state.pub_name}')"
`myslot1` 不可以写死了

2022-12-28 09:54 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +  #  end
如果不需要就删除吧

2022-12-28 09:59 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +        {:in_transaction, payload}
会。这些是依据文档，需要明确处理的。

2022-12-28 09:59 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +  end
ok

2022-12-28 10:00 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +      ]
ok。手误。未来及删改。：）

2022-12-28 10:00 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +    send(__MODULE__, {:ack, wal})
ok

2022-12-28 10:00 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +      "START_REPLICATION SLOT myslot1 LOGICAL 0/0 (proto_version '2', publication_names '#{state.pub_name}')"
ok

2022-12-28 10:05 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +      ]
嗯。实现 `broadway.producer` 的逻辑的第一步，得把 `pg` 的 `ack机制` 先确定。

我斟酌一下，改下这个 `PR` 的主题任务。争取不跑偏。

2022-12-28 10:06 UTC, json2008 commented
> 现在的实现没看到 broadway.producer 的相关逻辑哦，你这个 PR 的范围要不要改一下哦

嗯。实现 `broadway.producer` 的逻辑的第一步，得把 `pg` 的 `ack机制` 先确定。

我斟酌一下，改下这个 `PR` 的主题任务。争取不跑偏。

2022-12-28 10:15 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +    send(__MODULE__, {:ack, wal})
https://github.com/supabase/realtime/tree/develop/lib/extensions/postgres_cdc_stream

2022-12-29 02:44 UTC, json2008 commented
@fahchen 

把 `pr` 做了拆分。本 `pr` 仅用于完美 `pg_source ack` 机制。

下一个 `pr` 再来处理 `stateful decode`

2022-12-29 03:26 UTC, fahchen requested changes
[ ] 补充测试

2022-12-29 03:26 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +  end
给一个 struct 来作为 state 吧

2022-12-29 03:26 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +  def async_ack(server, lsn) when is_integer(lsn) do
```suggestion

  @spec async_ack(server(), lsn()) :: {:ack, lsn()}
  def async_ack(server, lsn) when is_integer(lsn) do
```

2022-12-29 03:26 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +  end
```suggestion
  defp ack_message(lsn) when is_integer(lsn) do
    [<<?r, lsn + 1::64, lsn + 1::64, lsn + 1::64, current_time()::64, 0>>]
  end
```

2022-12-29 03:26 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +    [<<?r, lsn + 1::64, lsn + 1::64, lsn + 1::64, current_time()::64, 0>>]
这三个 lsn 都填写一样的值吗？是不是不同的时候，填的值不一样
比如 client 收到了 message，那么这时第一个 lsn 的值应该是收到的最后一个 message 的 lsn，而后两个 lsn 则是对应的 ack 来了后才回复给 server

2022-12-29 03:26 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +    {:noreply, ack_messages(state[:fina_lsn]), state}
我们的 ack 是按接收顺序来的吗？
这里应该有可能下游的 ack 不是按顺序回来的，所以这里回复的 ack 需要是某一个 lsn 之前的所有的 message 的 ack 都回来了

2022-12-29 04:01 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +    {:noreply, ack_messages(state[:fina_lsn]), state}
按收到的`ack`，会与状态中保存的 `已回应的ack` 做比较。只回应更大的值。

2022-12-29 04:01 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +    [<<?r, lsn + 1::64, lsn + 1::64, lsn + 1::64, current_time()::64, 0>>]
参见官方文档，三个值，对我们来说，似乎可以一样 。

Int64
  The location of the last WAL byte + 1 received and written to disk in the standby.

Int64
  The location of the last WAL byte + 1 flushed to disk in the standby.

  Int64
  The location of the last WAL byte + 1 applied in the standby.

2022-12-29 04:02 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +  end
Done!

2022-12-29 04:02 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +  def async_ack(server, lsn) when is_integer(lsn) do
Done!

2022-12-29 04:02 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +  end
Done!

2022-12-29 04:02 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +  #  ]
Done!

2022-12-29 04:04 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +    {:noreply, ack_messages(state[:fina_lsn]), state}
Given: 现在的 message 有（lsn）：1，2，3，4
When: ack 的 message 有 4，3

这时不应该 ack 4

2022-12-29 04:05 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +    [<<?r, lsn + 1::64, lsn + 1::64, lsn + 1::64, current_time()::64, 0>>]
我感觉不太一样，比如第一个 lsn 我可以告诉 server 我收到了，但是还没有持久化，不算最终的 ack

2022-12-29 04:13 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +    {:noreply, ack_messages(state[:fina_lsn]), state}
以最大值为准。当已经回一个大的值，下游再送上来一个比它小的值，实际效果是：无意义。

2022-12-29 04:24 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +    {:noreply, ack_messages(state[:fina_lsn]), state}
假设下发的消息是，1，2，3，4，5

下游ack上来，1，4，3，2，5

实际ack给pg的是：1，4，4，4，5

2022-12-29 04:26 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +    [<<?r, lsn + 1::64, lsn + 1::64, lsn + 1::64, current_time()::64, 0>>]
那就很复杂了。做为第上游的`pg_source`，不应该关注这些。`ack`，就代表下游已经消费了。

2022-12-29 04:27 UTC, json2008 commented
@fahchen 

如果`ack`这块，有其它的需要，或是想法，后面可一并提出来，我再来统一修改。不费事。

2022-12-29 04:29 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +  end
改成 `struct` 的形式，的确好很多。

2022-12-29 06:30 UTC, fahchen requested changes

2022-12-29 06:30 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +    field :step, atom(), default: :disconnected
atom 写具体

2022-12-29 06:30 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +    [<<?r, lsn + 1::64, lsn + 1::64, lsn + 1::64, current_time()::64, 0>>]
那为什么设计三个 lsn？

2022-12-29 06:30 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +  ## Sample:
你这个 moduledoc 规范点写吧，写得太随意了

2022-12-29 06:30 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +    source_name: :my_pg_source,
```suggestion
    name: :my_pg_source,
```

2022-12-29 06:30 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +    conn_opts: [host: "localhost", database: "r704_development", username: "jswk"]
这个这里不用包一层，options 的参数这一层把要消费的 pop 出来，剩下的扔给 Replication Connection

2022-12-29 06:30 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +      end
认真一点
```suggestion
    {:noreply, ack_message(state.final_lsn), state}
```

2022-12-29 06:30 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +  they have been received by all standbys, and that the primary does not remove rows which could cause a recovery
更新 map 不用 struct/2 
```suggestion
    {:stream, query, [], %{state | step: :streaming}}
```

2022-12-29 06:53 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +  def start_link(opts) do
Done!

2022-12-29 06:53 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +    field :step, atom(), default: :disconnected
Done!

2022-12-29 07:07 UTC, fahchen requested changes

2022-12-29 07:07 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +  @spec async_ack(server(), lsn()) :: {:ack, lsn()}
```suggestion

  @spec async_ack(GenServer.server(), lsn()) :: {:ack, lsn()}
```

2022-12-29 07:07 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +    {:stream, query, [], struct(state, step: :streaming)}
更新 map 或 struct 不用 `struct/2`
```suggestion
    {:stream, query, [], %{state | step: :streaming}}
```

2022-12-29 07:11 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +      end
```elixir
  def handle_data(<<?k, _wal_end::64, _clock::64, reply>>, state) do
    message =
      case reply do
        1 -> ack_message(state.final_lsn)
        0 -> []
      end

    {:noreply, message, state}
  end
```

 如果按`review`去修改，语义会不同。任何时何，有心跳包来时（频繁），都要回应数据回去。
而文档上说明，当`reply = 0`， 可以不回应的？

```elixir
  def handle_data(<<?k, _wal_end::64, _clock::64, reply>>, state) do
    {:noreply, ack_message(state.final_lsn), state}
  end

2022-12-29 07:17 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +    {:stream, query, [], struct(state, step: :streaming)}
Done!

2022-12-29 07:17 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +  @spec async_ack(server(), lsn()) :: {:ack, lsn()}
Done!

2022-12-29 07:17 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +  they have been received by all standbys, and that the primary does not remove rows which could cause a recovery
Done!

2022-12-29 08:07 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +    {:noreply, ack_messages(state[:fina_lsn]), state}
给 pg 的 ack 应该不对，应该是：1, 1, 1, 4, 5

2022-12-29 09:49 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +           {:name, String.t()},
name 的签名有问题

2022-12-29 09:49 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +    {name, opts} = Keyword.pop!(opts, :name)
name 可以不是必填的，这个是有使用方决定的

2022-12-29 09:49 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +  @type lsn() :: integer() | String.t()
放到上面去，state 里面的 final_lsn 也用这个 type

2022-12-29 10:54 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +    {name, opts} = Keyword.pop!(opts, :name)
已修改。

2022-12-29 10:58 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +  @type lsn() :: integer() | String.t()
`struct`里面的`final_lsn()::integer()` 与此处的`lsn() :: integer()| String.t()`并不冲突。

待程序稳定后，可考虑将上一个`pr`中的，与`lsn`有关的类型，统一改为：`integer()`。

这样的话，在程序中，`lsn`就只有一种表示方式：`integer()`

2022-12-29 10:59 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +           {:name, String.t()},
学习了。

2022-12-29 11:01 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +        ?S -> %{state | in_transaction: true}
按沟通，暂切先按一层嵌套来处理。后面，如果查到文档或是测试数据出现多层嵌套时。再新开`pr`，来修正。

2022-12-30 02:33 UTC, fahchen requested changes

2022-12-30 02:33 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +  @spec async_ack(GenServer.server(), integer) :: {:ack, integer}
要不类型都加一个 `()` 吧，统一一下风格
```suggestion
  @spec async_ack(GenServer.server(), integer()) :: {:ack, integer()}
```

2022-12-30 03:57 UTC, json2008 commented
@fahchen 

`Github Action` 配置上了。已经可以连接到 `pg` 进行冒烟测试了 (成功）。

请帮看一下，我改动了 `eliixir.yml` 中，与 `pg` 有关的配置是否正确，符合规范要求？

2022-12-30 08:16 UTC, fahchen commented
> @fahchen
> 
> `Github Action` 配置上了。已经可以连接到 `pg` 进行冒烟测试了 (成功）。
> 
> 请帮看一下，我改动了 `elixir.yml` 中，与 `pg` 有关的配置是否正确，符合规范要求？
> 
> 冒烟测试中的 `PgSourceTestHelper`，是从 `Postgrex` 的测试中，借鉴过来的，比较方便。

CI 的配置没有大问题

2023-01-04 05:50 UTC, json2008 commented
@fahchen 

基本的 `ack` 测试已经通过了。

其中，`pg_source.ex` 中的有些写法，比如，状态中的： `queue`, `size`是为了兼容后面的 `broadway` 的调用而特别设置的。

请帮看下，指出不足的地方。

2023-01-04 06:25 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +        ?S -> %{state | in_transaction: true}
记到 issue，把 issue 的链接贴到这里

2023-01-04 06:25 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +        {:in_transaction, payload}
贴一下链接

2023-01-05 03:00 UTC, fahchen requested changes

2023-01-05 03:00 UTC, fahchen commented on lib/postgrex_wal/pg_source.ex
> +      [max_messages: 500],
这个参数为什么要设置成 500 呢？

2023-01-05 03:00 UTC, fahchen commented on lib/postgrex_wal/pg_source.ex
> +      {:noreply, %{state | queue: :queue.new(), size: 0}}
这里你看看能不能再简化一下，能用做测试就好了，因为 broadway 进来会改变这里的行为

2023-01-05 03:00 UTC, fahchen commented on test/pg_source_test.exs
> +  test "shold receive replication events with ack", context do
```suggestion
  test "should receive replication events with ack", context do
```

2023-01-05 03:00 UTC, fahchen commented on test/pg_source_test.exs
> +  test "without ack" do
这个和 `with ack` 那个测试用例没看出来区别呢

2023-01-05 03:00 UTC, fahchen commented on test/test_helper.exs
> +PostgrexWal.PSQL.cmd(sql_test)
这些放到每个测试用例的 setup 里面吧，这样可以并行跑测试

2023-01-05 09:35 UTC, json2008 commented on test/test_helper.exs
> +PostgrexWal.PSQL.cmd(sql_test)
Done!

2023-01-05 09:35 UTC, json2008 commented on test/pg_source_test.exs
> +  test "without ack" do
已经重构各个测试，并加上了注释。

2023-01-05 09:58 UTC, json2008 commented on lib/postgrex_wal/pg_source.ex
> +      [max_messages: 500],
默认参数就是500，而在此处写明，是为了后面提醒：这个参数可调整。

2023-01-05 09:58 UTC, json2008 commented on lib/postgrex_wal/pg_source.ex
> +      {:noreply, %{state | queue: :queue.new(), size: 0}}
Done!

2023-01-05 10:01 UTC, json2008 commented on lib/postgrex_wal/pg_source.ex
> +  end
Done!

2023-01-05 10:58 UTC, json2008 commented
@fahchen 

按 `Review` 所指出的，已经调整，修改过了。

此 `PR` 是用来完成 `ack 机制` 的。

如果没其它问题，可行的话，可否 `approve` 结束掉。

其它的与 `Broadway` 有关的，将在新的 `PR` 中，去完成？

2023-01-05 11:14 UTC, fahchen commented on lib/postgrex_wal/pg_source.ex
> +      [max_messages: 500],
提示可以写到文档或者 typespec 里面

2023-01-05 11:30 UTC, fahchen commented on .github/workflows/elixir.yml
> +          PG_SOCKET_DIR: /var/run/postgresql
贴一下代码链接

2023-01-06 01:39 UTC, fahchen commented
> @fahchen 
> 
> 
> 
> 按 `Review` 所指出的，已经调整，修改过了。
> 
> 
> 
> 此 `PR` 是用来完成 `ack 机制` 的。
> 
> 
> 
> 如果没其它问题，可行的话，可否 `approve` 结束掉。
> 
> 
> 
> 其它的与 `Broadway` 有关的，将在新的 `PR` 中，去完成？  

现在写的代码怎么被 producer 用起来你给一个例子说明一下。我觉得这个 PR 按 Broadway 的 producer 来写比较好。

2023-01-06 01:40 UTC, fahchen commented
另外，PR 的 description 维护起来，参考 handbook 更新一下这个 PR 的 description

2023-01-06 01:42 UTC, fahchen requested changes
按 Broadway 的 Producer 来抽象吧

2023-01-06 01:42 UTC, fahchen commented on test/pg_source_test.exs
> +  test "pg logical replication ack test", context do
测试别合并在一个 case 里面了吧，可以拆开一下

2023-01-06 01:42 UTC, fahchen commented on test/support/postgrex_wal/pg_source_relayer.ex
> +defmodule PostgrexWal.PgSourceRelayer do
这个文件不是必须的，直接在 case 里面 subscribe 就好了

2023-01-06 02:13 UTC, fahchen commented on test/pg_source_test.exs
> +    n = :rand.uniform(100_000)
可以试试通过 `context` 获取到当前的 test 的 name，然后 `:erlang.phase2/1` 来生成一个 hash

2023-01-06 03:05 UTC, json2008 commented on test/pg_source_test.exs
> +    n = :rand.uniform(100_000)
知道这种用法。

`:erlang.phash2(context.module)` 仅仅是将一个固定值，散列成另一个固定值。与测试模块的名称绑定。

当时觉得 `:rand.uniform/1` 简单，并是随机值。能满足要求。

ok。已按意见修改了。

2023-01-06 03:08 UTC, json2008 commented on test/support/postgrex_wal/pg_source_relayer.ex
> +defmodule PostgrexWal.PgSourceRelayer do
是测试所需要的 `helper`，所以放在 `test/support` 下了。

它用于 解码、分组消息。缺少它，测试会比较麻烦。

不仅是这个 `case`，后面其它测试或许也会借用到。

2023-01-06 03:13 UTC, json2008 commented on test/pg_source_test.exs
> +  test "pg logical replication ack test", context do
原本是写成一个 `case` 下的，多个 `test`中。
但种个 `test` 需要按 `seed 0`，顺序执行。
当初之所以这样写，是想借用：每个 `test` 执行、退出时，`pg_repl`也会自动重启。

因为存在这种问题依赖问题，以及可能与其它 `case` 的相互影响，所以改成现在这样。

这种 `ack` 测试，是需要集成在一个 `test`中，前一步的行为，会在下一步去 `assert`。分拆了，可能反而不好弄。

2023-01-06 03:24 UTC, json2008 commented on test/pg_source_test.exs
> +    n = :rand.uniform(100_000)
知道这种用法。

`:erlang.phash2(context.module)` 仅仅是将一个固定值(模块名)，散列成另一个固定值（长度不定的数字）。
与测试模块的名称绑定。

当时觉得 `:rand.uniform/1` 简单，并是随机值。能满足要求。

ok。已按意见修改了。

2023-01-10 08:06 UTC, json2008 commented
@fahchen 

`broadwary` & `producer` 推一个初版，不知方案是否合适？

2023-01-10 09:14 UTC, fahchen commented on test/pg_source_test.exs
> +  test "pg logical replication ack test", context do
每一个 case 有它的 setup，你构建干净的测试环境给每一个 case 就好了

2023-01-10 09:16 UTC, fahchen commented on test/pg_source_test.exs
> +    n = :rand.uniform(100_000)
没问题哈，这里我的出发点是让每个 case 的 n 固定下来，方便 debug，因为用随机数，我们没有办法确定 n 是多少，就不知道对应的 table name

2023-01-10 09:18 UTC, fahchen commented on test/support/postgrex_wal/pg_source_relayer.ex
> +defmodule PostgrexWal.PgSourceRelayer do
等下我和你一起写

2023-01-10 09:24 UTC, json2008 commented on .github/workflows/elixir.yml
> +          PG_SOCKET_DIR: /var/run/postgresql
https://github.com/Byzanteam/postgrex_wal/pull/16/files#diff-c392f20dd0e6f1ad826ba281f42dbff2f8098505cf9e7307027ee2b9e9d7cfe2

2023-01-10 09:31 UTC, json2008 commented on test/pg_source_test.exs
> +  test "shold receive replication events with ack", context do
typo. :)

2023-01-10 09:34 UTC, json2008 commented on test/pg_source_test.exs
> +  test "pg logical replication ack test", context do
了解。

当前只有一个 `test case`，且 只有一个 `test`

2023-01-10 09:36 UTC, json2008 commented on lib/postgrex_wal/pg_source.ex
> +  @moduledoc false
现在，还在补 `Broadway Producer` 进来，待稳定后，一并将 `@moduledoc` 补齐。

2023-01-10 09:36 UTC, json2008 commented on test/pg_source_test.exs
> +    n = :rand.uniform(100_000)
了解学习了。

2023-01-11 01:49 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +        {:in_transaction, payload}
没有明确的那个链接讲述这个。大部分会带有`transaction_id`,但个别，如`origin`消息，没有。

相关文档，可见：`Orgin.decode/1`代码中的`@doc`.

2023-01-11 01:55 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source.ex
> +  @type lsn() :: integer() | String.t()
现在这个问题已经不存在在了。

`state struct` 里面的`final_lsn`的类型定义为：`integer()`

其它地方（仅一处），所用到的参数`lsn`的类型是：`String.t()`

直接定义了。没必要再专们做一个自定义的`lsn`类型了。

2023-01-11 02:03 UTC, json2008 commented on .github/workflows/elixir.yml
> +          PG_SOCKET_DIR: /var/run/postgresql
云端集成环境中，配置上默认的环境变量的目的：
1. 告诉使用者默认的用户名及密码。并配置在环境变量中。可直接使用。
2. 但本地测试，用户、密码、库等都可能不一样，所以，测试代码中，又会明确再设置一次。
3. 这样，本地，云端的测试都可跑起来。

2023-01-11 02:07 UTC, json2008 commented on lib/postgrex_wal/pg_source.ex
> +      [max_messages: 500],
`@type stream_opts() :: [{:max_messages, pos_integer()}]`

相关的文档，已经做在了相关代码`@doc`里了。

2023-01-11 02:26 UTC, json2008 commented
> > @fahchen
> > 按 `Review` 所指出的，已经调整，修改过了。
> > 此 `PR` 是用来完成 `ack 机制` 的。
> > 如果没其它问题，可行的话，可否 `approve` 结束掉。
> > 其它的与 `Broadway` 有关的，将在新的 `PR` 中，去完成？
> 
> 现在写的代码怎么被 producer 用起来你给一个例子说明一下。我觉得这个 PR 按 Broadway 的 producer 来写比较好。

更新了项目的 `README.md`，对项目的相关以及使用做了简短描述。

2023-01-11 02:38 UTC, json2008 commented on lib/postgrex_wal/pg_source.ex
> +  @moduledoc false
`pg_source.ex` 中的 `@moduledoc`，已经补上。

2023-01-11 02:39 UTC, json2008 commented on test/support/postgrex_wal/pg_source_relayer.ex
> +defmodule PostgrexWal.PgSourceRelayer do
已将经合并进来。

2023-01-11 06:55 UTC, json2008 commented
@fahchen 

协同编程中，你演示的测试代码已经合并进来了。

上面的 `conversation` 我逐一处理并回复了。

空时请帮 `review` 下。

PS：一些该分散处理的问题，我已经列到新创建的 `issue`中了。

2023-01-11 09:09 UTC, fahchen requested changes

2023-01-11 09:09 UTC, fahchen commented on lib/postgrex_wal/pg_source.ex
> +    # Behaviour maybe changed when introduce Broadway.
适当给一些 tag

```suggestion
    # FIXME: Behaviour maybe changed when introduce Broadway.
```
或
```suggestion
    # TODO: Behaviour maybe changed when introduce Broadway.
```

2023-01-11 09:09 UTC, fahchen commented on lib/postgrex_wal/pg_source.ex
> +    {:noreply, %{state | subscriber: pid}}
这里处理方式有问题，你需要把之前之前的 pid `demonitor`，才能覆盖

2023-01-11 09:09 UTC, fahchen commented on lib/postgrex_wal/pg_source.ex
> +  end
```suggestion
  def handle_info({:DOWN, _ref, :process, pid, _reason}, %{subscriber: pid} = state) do
    {:noreply, %{state | subscriber: nil}}
  end
  
  def handle_info({:DOWN, _ref, :process, pid, _reason}, state) do
    # log or ignore
    {:noreply, state}
  end
```

2023-01-11 09:09 UTC, fahchen commented on test/pg_source_test.exs
> +    ]
cmd 和 opts 用同一处配置

2023-01-11 09:09 UTC, fahchen commented on lib/postgrex_wal/producer.ex
> +defmodule PostgrexWal.Producer do
这个 module 测试忘写了？

2023-01-11 09:18 UTC, json2008 commented on test/pg_source_test.exs
> +    ]
你留言有一个TODO，把这个移到config配置里去？

2023-01-11 09:20 UTC, fahchen commented on test/pg_source_test.exs
> +    ]
我觉得用环境变量更好一些，可以不引入 config

2023-01-11 09:20 UTC, json2008 commented on lib/postgrex_wal/producer.ex
> +defmodule PostgrexWal.Producer do
没忘记。做到 # 18 里了。构造测试用例很耗时。这个PR里是完不成的。

原本这个PR仅用于`ack`的测试，你前次的`Review`中，提出，要加一个类似demo的实现方式？

2023-01-11 09:29 UTC, json2008 commented on lib/postgrex_wal/pg_source.ex
> +  end
拆分了的确清晰，且函数式。

这个函数将在 #21 中删除掉。就不再提交对这个修改。学习了。

2023-01-11 09:31 UTC, json2008 commented on lib/postgrex_wal/pg_source.ex
> +    {:noreply, %{state | subscriber: pid}}
这块我当初对需求不太清晰，有些过度设计，凭想像在设计。

这个函数将在 #21 中删除掉。就不再提交对这个修改。学习了。

2023-01-11 09:32 UTC, fahchen commented on lib/postgrex_wal/producer.ex
> +defmodule PostgrexWal.Producer do
没有测试，这个 PR 就先不加这个 module

2023-01-11 09:33 UTC, json2008 commented on lib/postgrex_wal/pg_source.ex
> +    # Behaviour maybe changed when introduce Broadway.
考虑过。所以用词是`maybe changed`。

因为不知道后面需求会是怎样的，会怎样改变，所以不确定会不会调整。只能是`maybe` 一下。

另外，如果加 `todo` 或 `fixme` 后，代码检查严格，不过。。

2023-01-11 09:36 UTC, json2008 commented on lib/postgrex_wal/pg_source.ex
> +  	   username: "jswk"
Done!

2023-01-11 09:43 UTC, json2008 commented on lib/postgrex_wal/my_broadway.ex
> +defmodule MyBroadway do
ok

已经移到 `pg_source.ex` 的 `@moduledoc`里，做为`Example`

2023-01-11 09:51 UTC, json2008 commented on config/test.exs
> +  username: "postgres"
ok

```elixir
    [
      table_name: table_name,
      opts: [
        publication_name: publication_name,
        slot_name: slot_name,
        database: System.get_env("WAL_DB", "postgres"),
        host: System.get_env("WAL_HOST", "localhost"),
        username: System.get_env("WAL_USERNAME", "postgres")
      ]
    ]
  end
```

2023-01-11 09:57 UTC, fahchen commented on lib/postgrex_wal/pg_source.ex
> +    # Behaviour maybe changed when introduce Broadway.
可以暂时 disable 一下这里的 credo 检查
https://hexdocs.pm/credo/config_comments.html

2023-01-11 10:27 UTC, json2008 commented on lib/postgrex_wal/producer.ex
> +defmodule PostgrexWal.Producer do
ok

删除掉了。

2023-01-11 10:29 UTC, json2008 commented on .github/workflows/elixir.yml
> +          - /var/run/postgresql:/var/run/postgresql
ok

也删除掉了。

2023-01-11 10:43 UTC, json2008 commented on lib/postgrex_wal/pg_source.ex
> +    # Behaviour maybe changed when introduce Broadway.
\# credo:disable-for-this-file Credo.Check.Design.TagTODO

已经用这个，解决掉了。学习了。

2023-01-11 11:47 UTC, fahchen requested changes

2023-01-11 11:47 UTC, fahchen commented on lib/postgrex_wal/pg_source.ex
> +# credo:disable-for-this-file Credo.Check.Design.TagTODO
这个留在对应的那一行吧因为这个是个临时的 disable，到时候处理好一并删除，放这里容易忘

2023-01-11 11:47 UTC, fahchen commented on test/pg_source_test.exs
> +    pg_env = PostgrexWal.PSQL.pg_env()
```suggestion
    pg_env = PSQL.pg_env()
```

2023-01-11 11:47 UTC, fahchen commented on test/support/postgrex_wal/psql.ex
> +      {output, status} = System.cmd("psql", args, stderr_to_stdout: true, env: pg_env())
这样写你就不用环境变量就可以调整下了，不用和 psql 需要的环境变量对齐，没有下划线风格看着不是特别舒服


```suggestion
    env = pg_env()
    database_url = "postgres://#{env[:username}}:#{env[:password]}@#{env[:host]}:#{env[:port]}/#{env[:database]}"

    for q <- List.wrap(query) do
      args = [database_url, "-c", q]
      {output, status} = System.cmd("psql", args, stderr_to_stdout: true)
```

```elixir
  def pg_env do
    [
      username: System.get_env("PG_USERNAME", "postgres"),
      # snip
    ]
   end
```

2023-01-11 11:47 UTC, fahchen commented on test/support/postgrex_wal/psql.ex
> +        raise "PSQL.cmd error"
可以整个 raise error，怎样醒目一些，现在只会看到红色的 `"PSQL.cmd error"`，然后再去找上面的默认颜色的 `IO.puts`

2023-01-11 11:47 UTC, fahchen commented on test/support/postgrex_wal/psql.ex
> +        $ createuser postgres -s --no-password
你这段提示有问题，我们这里不需要 postgres user 存在，实际上我们也不会创建 databases 和 users，下面提示的那个命令也不合适。根据实际情况调整一下

2023-01-11 11:47 UTC, fahchen commented on test/test_helper.exs
> +  capture_log: false
没有改动就不动哈

```suggestion
  refute_receive_timeout: 1_000
```

2023-01-11 11:47 UTC, fahchen commented on lib/postgrex_wal/pg_source.ex
> +       end
还没做成 GenStage 的 producer，你这个样例代码能跑起来吗？

2023-01-11 11:47 UTC, fahchen commented on README.md
> +## Other Info
写一段解释一下如何测试，类似： https://github.com/elixir-ecto/ecto#running-tests

2023-01-12 04:34 UTC, fahchen commented on test/test_helper.exs
> +  capture_log: false
你看上面提的改动建议，是把 capture_log 删除

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request

2023-01-12 04:35 UTC, fahchen commented on lib/postgrex_wal/pg_source.ex
> +       end
你现在这个 PR 的内容可以用这个启动起来吗？

2023-01-12 04:36 UTC, fahchen commented on README.md
> +## Other Info
放哪里的，链接贴一下

2023-01-12 05:46 UTC, json2008 commented on README.md
> +## Other Info
#18

2023-01-12 05:49 UTC, json2008 commented on test/test_helper.exs
> +  capture_log: false
按被子里理解：“没有改动就不动哈”， 我以为是说，可删可不删，如果没删，就别删？

删除了。Done！

2023-01-12 05:50 UTC, json2008 commented on test/test_helper.exs
> +  capture_log: false
我按字面去理解你的留言：“没有改动就不动哈”，意思是：可删除可不删除，如果没删除就保留？

所以，就没动。保留着没删除。

现在理解了。删除了。Done!

2023-01-12 05:55 UTC, json2008 commented on lib/postgrex_wal/pg_source.ex
> +       end
是可以了，我私下里测试过，用这个`GenStage Producer`，是可以用数据从`pipe line` 出来。调试过，消息自动会调用`ack`。

初步都正常。

改用：transform 方案，把 `GenStage Producer`，挂到`MyBroadway`，也可冒烟。

2023-01-12 05:57 UTC, json2008 commented on README.md
> +## Other Info
ISSUE #18

2023-01-12 07:38 UTC, fahchen requested changes

2023-01-12 07:38 UTC, fahchen commented on lib/postgrex_wal/pg_source.ex
> +       end
我启动不起来呢，相关配置如下

### 数据库信息：
```

postgrex_wal_test=# select * from pg_publication;
  oid  |     pubname      | pubowner | puballtables | pubinsert | pubupdate | pubdelete | pubtruncate | pubviaroot
-------+------------------+----------+--------------+-----------+-----------+-----------+-------------+------------
 16435 | postgrex_example |       10 | t            | t         | t         | t         | t           | f
 17521 | users            |       10 | f            | t         | t         | t         | t           | f
(2 rows)

postgrex_wal_test=# select * from pg_replication_slots;
   slot_name   |  plugin  | slot_type | datoid |     database      | temporary | active | active_pid | xmin | catalog_xmin | restart_lsn | confirmed_flush_lsn | wal_status | safe_wal_size | two_phase
---------------+----------+-----------+--------+-------------------+-----------+--------+------------+------+--------------+-------------+---------------------+------------+---------------+-----------
 slot_35691523 | pgoutput | logical   |  16384 | postgrex_wal_test | f         | f      |            |      |          923 | 0/1C15AD0   | 0/1C15B08           | reserved   |               | f
 example       | pgoutput | logical   |  16384 | postgrex_wal_test | f         | f      |            |      |          923 | 0/21DD488   | 0/21DD4C0           | reserved   |               | f
(2 rows)


```
### 启动脚本
```elixir
opts = [
  name: :example_pg_source,
  publication_name: "postgrex_example",
  slot_name: "example",
  host: "localhost",
  database: "postgrex_wal_test",
  username: "postgres"
]

MyBroadway.start_link opts
```

### error 如下
```elixir
{:error,
 {{:badmatch,
   {:error,
    {:shutdown,
     {:failed_to_start_child, #Reference<0.1007443476.3008626689.180196>,
      {:shutdown,
       {:failed_to_start_child, MyBroadway.Broadway.Producer_0,
        {:undef,
         [
           {PostgrexWal.Producer, :init,
            [
              [
                broadway: [
                  index: 0,
                  hibernate_after: 15000,
                  batchers: [],
                  context: :context_not_set,
                  resubscribe_interval: 100,
                  max_seconds: 5,
                  max_restarts: 3,
                  shutdown: 30000,
                  name: MyBroadway,
                  producer: [
                    hibernate_after: 15000,
                    transformer: nil,
                    module: {PostgrexWal.Producer,
                     [
                       name: :example_pg_source,
                       publication_name: "postgrex_example",
                       slot_name: "example",
                       host: "localhost",
                       database: "postgrex_wal_test",
                       username: "postgres"
                     ]},
                    concurrency: 1
                  ],
                  processors: [
                    default: [
                      hibernate_after: 15000,
                      max_demand: 10,
                      concurrency: 10
                    ]
                  ]
                ],
                name: :example_pg_source,
                publication_name: "postgrex_example",
                slot_name: "example",
                host: "localhost",
                database: "postgrex_wal_test",
                username: "postgres"
              ]
            ], []},
           {Broadway.Topology.ProducerStage, :init, 1,
            [file: 'lib/broadway/topology/producer_stage.ex', line: 70]},
           {GenStage, :init, 1, [file: 'lib/gen_stage.ex', line: 1731]},
           {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 848]},
           {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 811]},
           {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}
         ]}}}}}}},
  [
    {Broadway.Topology, :init, 1, [file: 'lib/broadway/topology.ex', line: 58]},
    {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 848]},
    {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 811]},
    {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}
  ]}}
** (EXIT from #PID<0.325.0>) shell process exited with reason: an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, {:shutdown, {:failed_to_start_child, #Reference<0.1007443476.3008626689.180196>, {:shutdown, {:failed_to_start_child, MyBroadway.Broadway.Producer_0, {:undef, [{PostgrexWal.Producer, :init, [[broadway: [index: 0, hibernate_after: 15000, batchers: [], context: :context_not_set, resubscribe_interval: 100, max_seconds: 5, max_restarts: 3, shutdown: 30000, name: MyBroadway, producer: [hibernate_after: 15000, transformer: nil, module: {PostgrexWal.Producer, [name: :example_pg_source, publication_name: "postgrex_example", slot_name: "example", host: "localhost", database: "postgrex_wal_test", username: "postgres"]}, concurrency: 1], processors: [default: [hibernate_after: 15000, max_demand: 10, concurrency: 10]]], name: :example_pg_source, publication_name: "postgrex_example", slot_name: "example", host: "localhost", database: "postgrex_wal_test", username: "postgres"]], []}, {Broadway.Topology.ProducerStage, :init, 1, [file: 'lib/broadway/topology/producer_stage.ex', line: 70]}, {GenStage, :init, 1, [file: 'lib/gen_stage.ex', line: 1731]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 848]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 811]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}}}}}
        (broadway 1.0.5) lib/broadway/topology.ex:58: Broadway.Topology.init/1
        (stdlib 4.0) gen_server.erl:848: :gen_server.init_it/2
        (stdlib 4.0) gen_server.erl:811: :gen_server.init_it/6
        (stdlib 4.0) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

```

2023-01-12 07:50 UTC, json2008 commented on test/support/postgrex_wal/psql.ex
> +  """
这里留的原来的CI测试环境中的环境变量，与代码里的变量名，不是同一个。

这个@doc，没什么意义了。删除了。可以从`elixir.ylm`中，看到相关的信息。

2023-01-12 09:31 UTC, json2008 commented on README.md
> +## Other Info
@fahchen 

这个`Issue`是你创建的，我编辑了下里面的`Todo List`的确没看到你的`Comments` ?

2023-01-12 12:20 UTC, fahchen commented
更新一下 PR 的描述，描述用英语写吧，因为你会直接把描述作为合并后的 commit message

2023-01-13 01:38 UTC, merged