postgrex_wal draft version
Byzanteam/postgrex_wal pull request #9
Opened 2022-12-01 06:04 UTC by json2008

First draft for postgrex_wal from GloryHonor

2022-12-01 06:58 UTC, fahchen requested changes
你在 readme 里面更新一下如何使用这个 lib，我有点看不懂我们怎么使用这个 lib 的

2022-12-01 06:58 UTC, fahchen commented on .gitignore
> +# composer.lock
composer 相关的不应该打进来哦

2022-12-01 06:58 UTC, fahchen commented on .gitignore
> +.idea/**/libraries
这部分不建议打进来，这部分作为 user 的 gitignore 存在就好了，不需要打进项目里面

2022-12-01 06:58 UTC, fahchen commented on .gitignore
> +.apdisk
这个文件我建议不要动了，你把你本地的一些自己的配置打进来了，不是属于这个 repo 的

2022-12-01 06:58 UTC, fahchen commented on config/runtime.exs
> +#config :postgrex_wal, :secret_key, System.fetch_env!("PG_REPL_INFO")
这个文件没用到，可以移除了

2022-12-01 06:58 UTC, fahchen commented on lib/postgrex_wal/application.ex
> +    IO.puts "--- start #{__MODULE__} ---"
这个不用打印出来哈，如果需要走 Logger 吧

2022-12-01 06:58 UTC, fahchen commented on lib/postgrex_wal/supervisor/gen_stage.ex
> +defmodule Postgrex.Supervisor.GenStage do
```suggestion
defmodule PostgrexWal.Supervisor.GenStage do
```

2022-12-01 06:58 UTC, fahchen commented on mix.exs
> +      {:pgoutput_decoder, "~> 0.1.0"}
走我们的 messages 去 decode 哈，不走这个 lib

2022-12-01 06:58 UTC, fahchen commented on lib/postgrex_wal/application.ex
> +  end
这里没有自定义的代码就不用写这部分哈

2022-12-01 06:58 UTC, fahchen commented on lib/postgrex_wal/gen_stage/mocked_consumer.ex
> +defmodule PostgrexWal.GenStage.MockedConsumer do
mocker 写到 test 文件夹下面去吧

2022-12-01 06:58 UTC, fahchen commented on test/postgrex_wal_test.exs
> +    Process.sleep(:timer.seconds(1))
这里的做法不妥，可以让 Consumer 那比把收到的 events 通过 `send/2` 发送到当前的 process

2022-12-01 06:58 UTC, fahchen commented on test/postgrex_wal_test.exs
> +    assert events_is_a?("Insert")
这里应该要断言 event 里面的 fields 是否是我们期待的

2022-12-01 06:58 UTC, fahchen commented on lib/postgrex_wal/registry.ex
> +defmodule PostgrexWal.Registry do
这个模块没看到用的地方呢？

2022-12-01 06:58 UTC, fahchen commented on lib/postgrex_wal/application.ex
> +defmodule PostgrexWal.Application do
这个 application 应该是不用设计到这个 lib 里面的，因为这个 lib 只负责给对应的 producer 的 module，具体怎么去 supervise 这部分是使用这个 lib 那里去实现的

2022-12-01 07:05 UTC, json2008 commented on lib/postgrex_wal/registry.ex
> +defmodule PostgrexWal.Registry do
原来考虑的复杂些。准备用它来做dynamic_job_dispatch

2022-12-01 07:06 UTC, json2008 commented on lib/postgrex_wal/application.ex
> +defmodule PostgrexWal.Application do
ok, 知道了。

2022-12-01 07:07 UTC, json2008 commented on test/postgrex_wal_test.exs
> +    assert events_is_a?("Insert")
字段特别多、杂。这个确保收到正确类型的event。
我考虑下如何改。

2022-12-01 07:08 UTC, json2008 commented on test/postgrex_wal_test.exs
> +    Process.sleep(:timer.seconds(1))
ok，我把fake_consumer做到测试里。

2022-12-01 07:08 UTC, json2008 commented on lib/postgrex_wal/gen_stage/mocked_consumer.ex
> +defmodule PostgrexWal.GenStage.MockedConsumer do
提醒的对。：）

2022-12-01 07:08 UTC, json2008 commented on lib/postgrex_wal/application.ex
> +    IO.puts "--- start #{__MODULE__} ---"
好。

2022-12-01 07:09 UTC, json2008 commented on config/runtime.exs
> +#config :postgrex_wal, :secret_key, System.fetch_env!("PG_REPL_INFO")
原本打算，在runtime时，从os env中读取pg连接信息？

2022-12-01 07:09 UTC, json2008 commented on .gitignore
> +.apdisk
ok

2022-12-01 07:09 UTC, json2008 commented on .gitignore
> +.idea/**/libraries
ok

2022-12-01 07:10 UTC, json2008 commented on .gitignore
> +# composer.lock
ok

2022-12-02 02:13 UTC, fahchen reviewed
ack 的机制我觉得有点问题
应该是当 consumer 消费完 events 后才去 pg 那边 ack

2022-12-02 02:13 UTC, fahchen commented on test/postgrex_wal_test.exs
> +    assert events_is_a?("Insert")
可以用 `match?/2`

2022-12-02 02:13 UTC, fahchen commented on test/postgrex_wal_test.exs
> +      |> Enum.any?(&(&1 |> Map.get(:__struct__) |> Atom.to_string |> String.ends_with?(str)))
这里用 `is_struct/2` 应该能满足你的用法

2022-12-02 02:13 UTC, fahchen commented on test/test_helper.exs
> +end
这个写到 `test/support/` 文件夹里面

2022-12-02 02:13 UTC, fahchen commented on lib/postgrex_wal/gen_stage/pg_source_relayer.ex
> +      |> PgoutputDecoder.decode_message
用我们自己的 Messages 做 decode 哈

2022-12-02 02:21 UTC, fahchen requested changes
~~ack 的机制我觉得有点问，当 consumer 消费完 events 后才去 pg 那边 ack~~

2022-12-02 05:48 UTC, json2008 commented on mix.exs
> +      {:pgoutput_decoder, "~> 0.1.0"}
可以

2022-12-02 05:48 UTC, json2008 commented on lib/postgrex_wal/application.ex
> +  end
ok

2022-12-02 05:55 UTC, json2008 commented on test/postgrex_wal_test.exs
> +      |> Enum.any?(&(&1 |> Map.get(:__struct__) |> Atom.to_string |> String.ends_with?(str)))
嗯。抓紧学习熟悉类库函数。

2022-12-02 06:05 UTC, json2008 commented on test/test_helper.exs
> +Process.register(pg_pid, PgConn)
测试前，这些都得启动，不然会没有replication events.

2022-12-02 06:06 UTC, json2008 commented on lib/postgrex_wal/gen_stage/pg_source_relayer.ex
> +      |> PgoutputDecoder.decode_message
ok。我尝试着改一下。

2022-12-02 06:06 UTC, json2008 commented on README.md
> +      },
学习了

2022-12-02 06:25 UTC, fahchen commented on test/test_helper.exs
> +Process.register(pg_pid, PgConn)
在对应的测试里面启动吧

2022-12-12 05:36 UTC, json2008 commented
刚开始尝试按 GitHub Flow 的流程来处理代码，好多地方不合规范。

我关闭这个PR，我重新做。@fahchen

2022-12-12 05:37 UTC, closed without merging